import base64
import tempfile
import unittest
from argparse import Namespace
from pathlib import Path
from unittest.mock import patch

from prusa_cli_preview.cli import (
    ThumbnailSpec,
    check_prusa_version,
    encode_thumbnail,
    inject_thumbnails,
    parse_thumbnail_specs,
    thumbnail_block,
)


class ThumbnailTests(unittest.TestCase):
    def test_png_encoding_allows_rendered_file_as_output(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "preview.png"
            path.write_bytes(b"png")
            encode_thumbnail(path, ThumbnailSpec(1, 1, "PNG"), path)
            self.assertEqual(path.read_bytes(), b"png")

    @patch("prusa_cli_preview.cli.run")
    def test_version_comes_from_help_banner(self, mocked_run):
        mocked_run.return_value.stdout = "PrusaSlicer-2.9.6+flathub.org based on Slic3r"
        args = Namespace(
            prusa_branch="stable",
            prusa_app="com.prusa3d.PrusaSlicer",
            require_version="2.9",
        )
        self.assertEqual(check_prusa_version(args), "2.9.6")
        self.assertEqual(mocked_run.call_args.args[0][-1], "--help")

    def test_parses_mixed_profile_formats(self):
        gcode = """; generated by PrusaSlicer 2.9.6
; thumbnails = 16x16/QOI, 220x124/QOI, 380x285/PNG
; thumbnails_format = PNG
"""
        self.assertEqual(
            parse_thumbnail_specs(gcode),
            [
                ThumbnailSpec(16, 16, "QOI"),
                ThumbnailSpec(220, 124, "QOI"),
                ThumbnailSpec(380, 285, "PNG"),
            ],
        )

    def test_thumbnail_block_declares_base64_size(self):
        payload = b"preview bytes"
        block = thumbnail_block(ThumbnailSpec(220, 124, "QOI"), payload)
        encoded = base64.b64encode(payload).decode("ascii")
        self.assertIn(f"thumbnail_QOI begin 220x124 {len(encoded)}", block)
        self.assertIn(encoded, block)
        self.assertIn("thumbnail_QOI end", block)

    def test_injection_follows_producer_header(self):
        source = "; generated by PrusaSlicer 2.9.6\n\nG28\n"
        result = inject_thumbnails(source, ["; thumbnail begin 1x1 4\n; AAAA\n; thumbnail end"])
        self.assertLess(result.index("thumbnail begin"), result.index("G28"))


if __name__ == "__main__":
    unittest.main()
